
#undef PRODUCT
#define PRODUCT         The Key v2

#undef RGBLED_NUM
#define RGBLED_NUM 5

#define RGBLIGHT_DEFAULT_HUE 192
#define RGBLIGHT_DEFAULT_SAT 255
#define RGBLIGHT_DEFAULT_VAL 96
#define RGBLIGHT_EFFECT_RAINBOW_SWIRL
#define RGBLIGHT_DEFAULT_MODE 4

#define PERMISSIVE_HOLD

#define TAPPING_TERM 200
